version: '3.8'


services:

  orders_api:
    build: .
    container_name: orders_api    
    environment:
      PYTHONUNBUFFERED: 1    
    volumes:
      - .:/app
    ports:
      - "4450:4450"
    env_file:
      - .env      
    depends_on:
      - mysql      
    restart: on-failure      

  mysql:
    image: mysql:9.0.1
    container_name: orders-mysql-db
    environment:
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: orders2024*
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d      
    ports:
      - "3306:3306"
    restart: on-failure